### ISSUE TITLE
problem with index ...

### ISSUE THREAD

**Issue by senkron24** [Simonmicro/Pritunl-Fake-API#1]
hi 
i wold first say thx for thsi great work ...

i have allready running and see thad the api its chnaged also no call home all lok like ok 

bud after i change or add www from your to /usr/share/pritunl/www nothing changed still not have ultimate 
i try to add licance i get this error 
Server error occurred, please try again later.

and if i try to acess from index.html to index.php 
404 page not found

i use the version 
v1.29.2591.94 2c70e4

also can you help pls to make it ultimate 👍 
its just privet ...

**Comment by Simonmicro** [comment]
Hi,
well before I'm going to further investigate this - could you please provide a little bit more information about your setup?

> bud after i change or add www from your to /usr/share/pritunl/www nothing changed still not have ultimate

This does not seem right. The files inside the `www` folder of this repository must be put on an own webserver. You could use any free hoster (https://infinityfree.net/) for that (I guess they must support SSL/TLS or HTTPS). When you have done that you can just execute the `setup.sh` on your Pritunl server. This script will rewrite the Pritunl source code to point to your new api endpoint (you could either use my publicly available or your own, which you have hosted somewhere else - as described before).

I recommend, that you try to use as first my public api endpoint - and when this work you could try to setup your own (by using the `www` folder).

I hope that helps.

**Comment by senkron24** [comment]
hi simonmicro 

yes its was my first hours to get runn the pritunl i was never use it befor 
also try to install on my dedicated server with this instration 
https://www.howtoforge.com/how-to-setup-a-vpn-server-using-pritunl-on-ubuntu-1804/

its works no problem bud its not enterprice i think becouse i not have same as yoru fotos like host etc missing 
only simple thinks add user add server etc..
also lok like its not enterprice
https://prnt.sc/vho5ul


after i sourch in internet i see your github was make me so happy to found samthing 👍 

also try to install from your github
python2 setup.py build
pip install -r requirements.txt
sudo python2 setup.py install

bud nothing changed still have same sw v1.29.2591.94 2c70e4
and not like your post in pritunl-1.29.2276.91
sure i have restart demond and all stuff 
and sure the instalation its giong not on /var/www
its located 
/usr/share/pritunl/www

bud any way its work standart not enterprice and cannot install on my bionic ubuntu 

can you help or mybe make a instartion for how to install the right sw on ubuntu 18.04 bionic 

kind regarts

**Comment by Simonmicro** [comment]
Ahhh, now I understand. Okay:
You'll need your normal Pritunl instance - like installed by your guide. Then you'll can setup the _seperate_ endpoint emulation server (`www` folder) - which has nothing to do with the Pritunl `www` folder! When you then want to modify Pritunl to use that server or my endpoint you'll need to execute the `setup.sh` script, which has nothing to do with any Python setup. You can just run it with `./setup.sh`!
And the version number in the "Update Notification" is just the latest version number I tested my endpoint emulator for...

**Comment by senkron24** [comment]
i will try :) hope will work )))
