### ISSUE TITLE
Sso not working. Do u have plan for fixing ?

### ISSUE THREAD

**Issue by songhanpoo** [Simonmicro/Pritunl-Fake-API#11]
First thing, i wanna appreciate your ideal. 
I have setup completed. But i cant use sso with active directory. Can u suggest anything for implement ?

**Comment by Simonmicro** [comment]
> SSO will not work with this api version! As Pritunls own authentication servers handle the whole SSO stuff, track instance ids and verify users I won't implement this part for privacy concerns (**and also this would need to be securly implemented and a database**).

You need to be more specific - what exactly do you propose?

**Comment by songhanpoo** [comment]
Hi! I'm only want to integrate AD. For user Vpn. Are you testing authen with radius ad?
> > SSO will not work with this api version! As Pritunls own authentication servers handle the whole SSO stuff, track instance ids and verify users I won't implement this part for privacy concerns (**and also this would need to be securly implemented and a database**).
> 
> 
> 
> You need to be more specific - what exactly do you propose?

**Comment by songhanpoo** [comment]
Hi !
I have intergrated with AD. many thanks. 
Can i ignore notification when login ?
![Screen Shot 2021-08-05 at 15 09 16](https://user-images.githubusercontent.com/33808968/128315306-4d83a2da-279e-478e-ac65-5903b555ffa1.png)

**Comment by Simonmicro** [comment]
Good to hear! Yes, this notification is just to let you know the crack is working.

**Comment by songhanpoo** [comment]
Hi! Can you brief explain when request to fake api ? 
I dont have experience with php.

**Comment by songhanpoo** [comment]
Hi @Simonmicro !

Many thanks.
