### ISSUE TITLE
Not working | No such file or directory

### ISSUE THREAD

**Issue by SindreMA** [simonmicro/Pritunl-Fake-API#12]
I'm having a problem setting this up.
I've tried to run it both on local install and the docker image, but both seam to return about the same error message.
That there is no such file or directory.

Any idea what this might be caused by, and how to fix it?

Docker image: 
![image](https://user-images.githubusercontent.com/29127320/130371021-3d8fdfa4-562e-48ad-88c9-daa480f9286d.png)

Local server image:
![image](https://user-images.githubusercontent.com/29127320/130371056-4103dfdc-1eac-4170-b612-7d9fbe9c4dd4.png)

**Comment by simonmicro** [comment]
The Docker container is fixed now - which Python version is running on your server -> e.g. which `python*` folder is inside `/usr/lib/`? I assume it is also Python 3.9

**Comment by SindreMA** [comment]
Cloned the github again now and it worked running locally. 
Tho i did try the docker image, it did build now, but had some problems running it, it failed on the pritunl setup.
But since i got the local server to work, i didn't look more into it.

Thanks for the help, great work making this 👍
