### ISSUE TITLE
pritunl v1.30.3108.50

### ISSUE THREAD

**Issue by MANKUD** [simonmicro/Pritunl-Fake-API#18]
Hello,

Could you please try to make your API work for the latest release pritunl v1.30.3108.50 as this release contains a fix for port forwarding on wireguard which is very crucial. if you are able to do it I would love to make a donation to support you.

**Comment by simonmicro** [comment]
Sure thing! Could you provide any logs what the current problem is? There is a good chance, that you have just missed to reapply the patch after updating :grin:

**Comment by MANKUD** [comment]
Hello,

I have tried it on a fresh installation on the latest release its just that
it says the license is activated as I remember but nothing happens.

**Comment by MANKUD** [comment]
The logs when I had checked it said invalid key.

**Comment by MANKUD** [comment]
Hello,

Would you be able to help me I would really appreciate it and maybe we can have a look together if you have time.

**Comment by MANKUD** [comment]
> Sure thing! Could you provide any logs what the current problem is? There is a good chance, that you have just missed to reapply the patch after updating 😁

Here are a few screenshots.

![image](https://user-images.githubusercontent.com/83474708/159057805-bb342533-84b9-4e1c-adeb-afaf88b198c9.png)

![image](https://user-images.githubusercontent.com/83474708/159057817-7de721e2-350d-4d87-ac5e-bdb8c6a1889f.png)

![image](https://user-images.githubusercontent.com/83474708/159057827-9b8ff9f9-5169-425d-a6a6-2152a0ef7a6c.png)

**Comment by simonmicro** [comment]
:rofl: - I see: https://github.com/pritunl/pritunl/commit/c1772d9b3268f91de409ad552e3d4d54d5ae1125

Guess I have to update the script to work with that... This will take a while, as I have pretty much no time :grin:

**Comment by MANKUD** [comment]
Oh, I see that now he has encoded it using base64. Will it be so hard since base64 is used?

**Comment by simonmicro** [comment]
No, but I will NOT update the setup for that - at least not using bash. I guess a few lines of Python will be enough for the future.

**Comment by MANKUD** [comment]
oh ok, may I know a timeline maybe? when can we expect an update from your end?

**Comment by simonmicro** [comment]
Could you be my BETA tester? Try this: [setup.py.zip](https://github.com/simonmicro/Pritunl-Fake-API/files/8307646/setup.py.zip)

**Comment by MANKUD** [comment]
sure I would love to let me try this :)

**Comment by simonmicro** [comment]
Nvm, I had not tested the script - it is broken... Working on that...

**Comment by simonmicro** [comment]
2nd try [setup.py.zip](https://github.com/simonmicro/Pritunl-Fake-API/files/8307764/setup.py.zip)

**Comment by MANKUD** [comment]
yes, I tried and it seems like its broken as you mentioned.

BTW I downgraded to pritunl v1.30.3102.46 (last version supported by your current fake API)and then ran your script which worked fine after that I manually replaced the wg port forwarding fix files i.e clients.py and instance.py and now the wg fix is working on an older version where your old fake api works.

**Comment by MANKUD** [comment]
> 2nd try [setup.py.zip](https://github.com/simonmicro/Pritunl-Fake-API/files/8307764/setup.py.zip)

let me give it a try

**Comment by MANKUD** [comment]
> 2nd try [setup.py.zip](https://github.com/simonmicro/Pritunl-Fake-API/files/8307764/setup.py.zip)

does not seem to be working I have to run this instead of your old script right?

**Comment by simonmicro** [comment]
Yes, this is strange... I'm investigating...

**Comment by MANKUD** [comment]
oh ok no problem take your time :)

**Comment by MANKUD** [comment]
Hi, the script ran successfully but the fake API emulation is not working. 

![image](https://user-images.githubusercontent.com/83474708/159089155-ac6c37dc-d778-4dc7-ab60-41d9dd46626b.png)

**Comment by MANKUD** [comment]
no pop up here

![image](https://user-images.githubusercontent.com/83474708/159089607-4b731892-30d3-456e-9080-44cae527de07.png)

![image](https://user-images.githubusercontent.com/83474708/159089477-cb86e2eb-61b9-488b-8730-360c53417f5a.png)

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/159090050-d1ecd861-f82d-42b8-83b6-0854847ee1e2.png)

**Comment by simonmicro** [comment]
Here we go again: [setup.py.zip](https://github.com/simonmicro/Pritunl-Fake-API/files/8307914/setup.py.zip)

**Comment by MANKUD** [comment]
oh ok great that was quick let me try.

**Comment by MANKUD** [comment]
looks like added 3 more things.

![image](https://user-images.githubusercontent.com/83474708/159091865-26ec4208-e3ee-43e6-885d-3893bcc4c18b.png)

![image](https://user-images.githubusercontent.com/83474708/159091869-92c29f17-2710-4562-b07b-52681e62b549.png)

**Comment by MANKUD** [comment]
looks like it did not work I cannot see advanced options for users :(

![image](https://user-images.githubusercontent.com/83474708/159092078-f66fd1b0-8acd-44bd-a584-c64ce3d656df.png)

**Comment by MANKUD** [comment]
`
![image](https://user-images.githubusercontent.com/83474708/159092248-91e7577f-395b-4f69-8537-6e78afa6e9b8.png)
`

**Comment by MANKUD** [comment]
`[ancient-dreams-6465][2022-03-18 22:16:56,873][ERROR] Exception on /subscription/styles/enterprise_plus/1003031084050.css [GET]
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/auth/app.py", line 19, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/handlers/subscription.py", line 44, in subscription_styles_get
    base64.b64decode(styles['data']).decode(),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
[ancient-dreams-6465][2022-03-18 22:16:56,873][ERROR] Exception on /subscription/styles/enterprise_plus/1003031084050.css [GET]
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/auth/app.py", line 19, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/handlers/subscription.py", line 44, in subscription_styles_get
    base64.b64decode(styles['data']).decode(),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
`

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/159092327-5d8771e9-087c-40c3-bf57-50b22270bd79.png)

**Comment by simonmicro** [comment]
Yes, I've just seen that error. Looks like they changed how the CSS file is passed on...

**Comment by MANKUD** [comment]
so it means more digging into it and adding more lines of code into the script?

**Comment by simonmicro** [comment]
Theoretically I just have to mitigate https://github.com/pritunl/pritunl/commit/70b354a10df55d60515f76d851dee42939864395 on my side...

...on it...

**Comment by simonmicro** [comment]
Done. I'll push everything soon :tm:

**Comment by MANKUD** [comment]
confirm? I did not understand tell me what I need to do?

**Comment by simonmicro** [comment]
Just restart your server after applying the script. I've just updated the api endpoint to be compatible with the newest version!

**Comment by MANKUD** [comment]
ok I am on it.

**Comment by MANKUD** [comment]
OMG perfect you are awesome looks like it is finally fixed.

![image](https://user-images.githubusercontent.com/83474708/159094101-32a31622-89db-429d-99e9-ec44584e67a3.png)

![image](https://user-images.githubusercontent.com/83474708/159094105-7e0c6116-548c-42f5-8d70-3d92f4bac084.png)

**Comment by MANKUD** [comment]
check your sponsor's page :)

**Comment by simonmicro** [comment]
Thank you very much :blush: :exploding_head:

**Comment by MANKUD** [comment]
Hello,

The script seems to be broken again on the latest release. Maybe the developer has again changed something.

![image](https://user-images.githubusercontent.com/83474708/159373553-9f2746d1-167d-4394-9a3d-b49b0e828ce5.png)

![image](https://user-images.githubusercontent.com/83474708/159373592-e72d07de-598a-4a63-8a56-02ec4b3e27d5.png)

![image](https://user-images.githubusercontent.com/83474708/159373621-d248389d-7cc0-4128-aaad-a16dfb8f91c9.png)

**Comment by simonmicro** [comment]
Just making sure: You rerun the `setup.py` after updating? Because I do not see any relevant code changes...

**Comment by MANKUD** [comment]
Yes, I already tried that it does not fix it. I think the changes are hidden this time may be as I too did not find any significant changes in the code related to this.

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/159374243-6580a67e-3595-4636-ba83-d68c353c8316.png)

**Comment by simonmicro** [comment]
Sadly both the Docker image (`goofball222/pritunl`) and the Debian packages (https://repo.pritunl.com/stable/apt/pool/) do not contain this version yet. Therefore I'm unable to investigate this (yet). Feel free to open up a new issue if the problem persist (even after a cold-boot of the server - maybe some caching is going on here?). Overall this seems very strange...

**Comment by MANKUD** [comment]
What I noticed is that the latest release is usually is not available as a package update via the repository and we have to manually download it using wget package name and then run dpkg -i package name to manually update to the latest release.

**Comment by simonmicro** [comment]
Argh sh*t. here we go again: https://github.com/pritunl/pritunl/commit/97f08a9ad634086cc19f38cfdd67cc93bc5eecb0

**Comment by MANKUD** [comment]
Yes, right I was about to share the same. Looks like the developer is following Pritunl-Fake-AP very closely 🤣 

Alright, I will open a new issue and you can take your time for this one no problem 😄

**Comment by MANKUD** [comment]
I see this now will it be even possible anymore? 

cipher = Cipher(
algorithms.AES(key),

**Comment by simonmicro** [comment]
Yes, it is - he uses symmetric encryption with not-so-secret secrets... BUT the faked API is written in PHP, so getting the proper "encryption" (more an obfuscation) running on the api side will be very challenging. Maybe I'll just ship a patch with the `setup.py` which reverts that "feature", but this is a little more intrusive than just changing the hard-coded endpoint URL. I'll have to think about this and won't fix this just as fast as his previous breaking change.

**Comment by MANKUD** [comment]
I totally understand and I would love to test it when you are able to make a patch for pritunl v1.30.3112.0 😄
