### ISSUE TITLE
"Server error occurred" on current version during activation

### ISSUE THREAD

**Issue by UltimateABC** [simonmicro/Pritunl-Fake-API#29]
hi

can i ask which version is working fine?

i tested many of them and all of tested on ubuntu  , i got an error 
**Server error occurred, please try again later.** message

![image](https://github.com/simonmicro/Pritunl-Fake-API/assets/3676067/23309aba-3634-4a0e-bf2b-725e4c29c1fb)

maybe my installation method is wrong, is there any step by step tutorials here?

**Comment by rfdrew** [comment]
+1 I have some error
![image](https://github.com/simonmicro/Pritunl-Fake-API/assets/20803599/4b3d2fbf-c791-4ec0-93b3-f76c5cc4b53b)
![image](https://github.com/simonmicro/Pritunl-Fake-API/assets/20803599/c04dab1c-1ba6-41f7-a0b1-5d69e7298dc2)
![image](https://github.com/simonmicro/Pritunl-Fake-API/assets/20803599/2d72bcdd-733b-4fc6-8fa9-cf8110bc0ef5)

**Comment by simonmicro** [comment]
1. Are you using an own hosted endpoint? If yes, does this error also appear on the public one?
2. Make sure to use PHP 8+. PHP 7 is end-of-life and the API now uses some functions from PHP 8 to make my life easier.

**Comment by simonmicro** [comment]
Additionally, I can observe a **large** amount of `473` errors on my api endpoint, as many users are trying to activate using too old clients (but no 500 -> so no server failures). I think they have to restart their Pritunl instance to view the notification, pointing out their too old client. Well... :man_shrugging: 

If you are affected, try checkout your instance logs and see if you have something interesting there :wink:

**Comment by UltimateABC** [comment]
i changed the endpoint API to your and worked fine.
thanks

**Comment by nd4y** [comment]
I deployed a FakeAPI server using a Self-Signed certificate. After adding the root certificate to the trusted list in /etc/ssl/certs/ca-certificates.crt on Pritunl, I still got the requests.exceptions.SSLError: HTTPSConnectionPool(host='pritunl-fakeapi.local', port=443) error: Max retries exceeded with url: /subscription (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))).

I found out that they use their own Python as part of the pritunl distribution and you need to add the root certificate to /usr/lib/pritunl/usr/lib/python3.9/site-packages/certifi/cacert.pem

**Comment by YuSyA55** [comment]
> I deployed a FakeAPI server using a Self-Signed certificate. After adding the root certificate to the trusted list in `/etc/ssl/certs/ca-certificates.crt` on Pritunl, I still got ` requests.exceptions.SSLError: HTTPSConnectionPool(host='pritunl-fakeapi.local', port=443) error: Max retries exceeded with url: /subscription (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))).`
> 
> I found out that they use their own Python as part of the pritunl distribution and you need to add the root certificate to `/usr/lib/pritunl/usr/lib/python3.9/site-packages/certifi/cacert.pem`

Good day.
Please tell me how you solved this error.
How can I correctly import my CA into this file?

**Comment by nd4y** [comment]
@YuSyA55 , Good day!
> How can I correctly import my CA into this file?

`cat ca.crt.pem | tee -a /usr/lib/pritunl/usr/lib/python3.9/site-packages/certifi/cacert.pem`
ca.crt.pem contains the certificate in PEM format
![Image](https://github.com/user-attachments/assets/1f2c7719-df99-4688-a865-c39cad5b3906)

**Comment by YuSyA55** [comment]
It works! Thanks!!!
