### ISSUE TITLE
Hi again :))

### ISSUE THREAD

**Issue by senkron24** [Simonmicro/Pritunl-Fake-API#3]
i wold ask i not be sure its ok like this for lisance like yours can you pls confirm thad like this ok ?

api lisance server : 

https://tvjoy.ml

**Comment by Simonmicro** [comment]
Looks good to me - it has HTTPS and reacts as expected to `[YOUR_URL]/notification`! But is seems like you have modified the code (there is a typo in your notification msg), please make sure to always use a non-modified version - as you would otherwise have to lay your modifications open!
