### ISSUE TITLE
Docker container can't restore default password 

### ISSUE THREAD

**Issue by namen3645** [simonmicro/Pritunl-Fake-API#32]
root@vultr:~/Pritunl-Fake-API-master/docker# docker exec -it docker_pritunl_1 bash pritunl default-password
/usr/bin/pritunl: line 3: import: command not found
/usr/bin/pritunl: line 4: import: command not found
/usr/bin/pritunl: line 7: __requires__: command not found
/usr/bin/pritunl: line 9: try:: command not found
/usr/bin/pritunl: line 10: from: command not found
/usr/bin/pritunl: line 11: except: command not found
/usr/bin/pritunl: line 12: try:: command not found
/usr/bin/pritunl: line 13: from: command not found
/usr/bin/pritunl: line 14: except: command not found
/usr/bin/pritunl: line 15: from: command not found
/usr/bin/pritunl: pritunl: line 18: syntax error near unexpected token `('
/usr/bin/pritunl: pritunl: line 18: `def importlib_load_entry_point(spec, group, name):'

**Comment by simonmicro** [comment]
You need to overwrite the entrypoint (`--entrypoint`), because the original creator did not only set the command.

This is due to this API using not the official container (as it did not exist back then), but instead one from the community.
