### ISSUE TITLE
Add SSO  Support

### ISSUE THREAD

**Issue by 4NE3Q** [simonmicro/Pritunl-Fake-API#35]
Hi,

Would you be so kind to add sso support or if you can ouline what needs to be done to make the sso work?

**Comment by simonmicro** [comment]
https://github.com/simonmicro/Pritunl-Fake-API/issues/11

https://github.com/simonmicro/Pritunl-Fake-API#nett2know

...well, take a look into the code and figure out which API request are sent to their backend, which this endpoint would need to emulate. I prefer not to hack-together SSO stuff in PHP, so I have neither the time nor intetest to implement that.

**Comment by 4NE3Q** [comment]
Thanks for your comment on this. All I want to know is which endpoint the API send request to their backend and I shall do it myself I don't want you to waste your valuable time, you've already done enough. Thanks.

**Comment by simonmicro** [comment]
Sorry, I cannot really answer this - and even if I would list all the needed endpoints here, you would still have to dig into the code itself to figure out their format and what these actually expect (doubt that they just 1:1 implemented OAuth2).

All in all I do not think it is worth investing time into this... Nowadays https://github.com/netbirdio/netbird looks like a really good alternative, which offer SSO out-of-the-box (they have no own user-backend and fully rely on an external IDP).
