### ISSUE TITLE
hi :)?

### ISSUE THREAD

**Issue by senkron24** [Simonmicro/Pritunl-Fake-API#4]
hi my freand i am sorry for this again :)

i have host the lisance files as you have written on the https root
its like 
https://tvjoy.ml
if i use this i get the error

Failed to load checkout data, please try again later.

bud if i use 
pritunl-api.simonmicro.de
working perfeckt no problems 
can you pls say me whats wrong i do pls :(

kind regarts

ps: i see on the logs like this its thad normal ?

SSLError: HTTPSConnectionPool(host='tvjoy.ml', port=443): Max retries exceeded with url: /subscription (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by Simonmicro** [comment]
Luckly you provided the logs:
```
SSLError: HTTPSConnectionPool(host='tvjoy.ml', port=443): Max retries exceeded with url: /subscription (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```
States that your SSL certificate for your HTTPS instance is invalid, when I visit your instance it is working fine. Make sure you used the `setup.py` correctly (you entered a new url starting with a HTTPS, not only HTTP) and your host OS for Pritunl is up-to-date. Except you can show me that the error is on my site (like a typo in my code) I can't really help you.
