### ISSUE TITLE
Nothing to change when run ./setup.sh

### ISSUE THREAD

**Issue by vquangna2** [Simonmicro/Pritunl-Fake-API#5]
Hi,
I have installed pritunl from source on this repository.
First, I get user/pass to login pritunl.
Then, I run ./setup.sh and restart pritunl
But when refresh browser, nothing to change!!

OS: Amazon Linux 2
----
What's the OS to use this scripts?
Thanks

**Comment by Simonmicro** [comment]
Hi, I tested & developed with Debian - could I get the installer logs? But I guess they are muted, so you may have to modify the setup script to use verbose commands (sry for that).

**Comment by vquangna2** [comment]
Oh, I think this scripts not compatible with my OS. `sed` command output syntax error.
Then I manual replace string via the editor and successful.
Thank you!
