### ISSUE TITLE
Error: Package 'dialog' missing!

### ISSUE THREAD

**Issue by WillyRL** [Simonmicro/Pritunl-Fake-API#6]
Hi,

Thank you for your wonderful works ! 
but when i'm try to run the server.sh

i got this 

`[root@Server1 server]# sudo sh setup.sh
Error: Package 'dialog' missing!`

**Comment by WillyRL** [comment]
Ah sorry,
solved by installing dialog package using yum.

Thank you

**Comment by WillyRL** [comment]
Hi @Simonmicro,

I'm successfully activate the enterprise license using your api, thats really great !! 
one of my question, is the enterprise feature all unlocked and working properly? like the clustering, etc 

Thanks

**Comment by Simonmicro** [comment]
Hi, thb I was not able to test everything to 100% - but if these features does not require communicating with other endpoints, they should work as expected. SAML for example runs exclusively on the Pritunl servers, so I'm unable to emulate this...
