### ISSUE TITLE
Syntax error: newline unexpected 

### ISSUE THREAD

**Issue by Mubbington** [Simonmicro/Pritunl-Fake-API#7]
The setup.sh file in server just says syntax error line 8 newline unexpected

**Comment by Simonmicro** [comment]
When does this error appear? When I execute the script in the current master branch it starts and opens up the dialog window.

**Comment by Simonmicro** [comment]
[Closing this issue soon, as necessary information is missing]

**Comment by MantyLang** [comment]
mub shut up
