### ISSUE TITLE
 Pull access denied

### ISSUE THREAD

**Issue by ScoobyDooWaffle** [Simonmicro/Pritunl-Fake-API#8]
Hi , just to let's you know 

ERROR: pull access denied for realsimonmicro/pritunl-with-fake-api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I think your dockers is locked i try to login and nothing success from it.

**Comment by Simonmicro** [comment]
Sadly I'm no longer able to provide this image - thanks to them: https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

Until they fix this, there is no modified image anymore :disappointed:
